### ISSUE TITLE
Rejection criteria

### ISSUE THREAD

**Issue by kambysese** [LABSN/mnefun#105]
@Eric89GXL can you explain what `_restrict_reject_flat` does exactly. It looks like rejection criteria cannot be `None` due to epoching and checking for DQs, correct?

**Comment by Eric89GXL** [comment]
I think it's just supposed to make it so that only relevant channels are included in the reject/flat dicts before they get passed to mne-python, but I'll have to take a closer look. You should be able to set no thresholds if you want, though. What problem are you hitting, you want to do no rejection but can't?

**Comment by kambysese** [comment]
Yes - I guess a more basic question is what is the DQ routine for? `_restrict_reject_flat` errors out when the rejection criteria are set to `None` and would presumably work to the same effect if thresholds are set excessively high.

**Comment by Eric89GXL** [comment]
> and would presumably work to the same effect if thresholds are set
excessively high.

You mean it throws an error if you set the threshold to np.inf? It
shouldn't. It should also work fine (not reject) if you pass an empty dict.
Do those both fail?
