### ISSUE TITLE
Down with OTP option

### ISSUE THREAD

**Issue by kambysese** [LABSN/mnefun#138]
@Eric89GXL how do you want to do this? Should `params.down_with_otp = False` be the switch for OTP inside the `do_sss` stage?

**Comment by Eric89GXL** [comment]
Heh, that would be funny.

Probably `otp_duration = None` (i.e., don't use) by default, any non-`None` value should be used as the duration.

OTP should be done on raw data (without any bad channels marked yet), so we actually need to make a new folder like `otp_fif` and store the resulting files there, and then process those files with MaxFilter. FYI it takes a long time to process the files, too.

The OTP files should be the ones inspected for bad channels, since it's likely that some that we would have marked as bad before will be fixed.

**Comment by kambysese** [comment]
Closing for now. Will revisit if anyone actually plans to use.
